wip : fix gh workflow

diff --git a/.github/workflows/build-devcontainer-image.yaml b/.github/workflows/build-devcontainer-image.yaml
--- a/.github/workflows/build-devcontainer-image.yaml
+++ b/.github/workflows/build-devcontainer-image.yaml
@@ -49,5 +49,9 @@ jobs:
             echo "PNPM environment : $(env | grep PNPM)"
             set -x
             echo "pnpm exec node --version=$(pnpm exec node --version || node --version || echo 'node not found')"
+            pnpm store path
+            ls -la $(pnpm store path)
+            pnpm env use --global 20.17.0
+            echo "pnpm exec node --version=$(pnpm exec node --version || node --version || echo 'node not found')"
 
 
