feat: separate release process in pre-release and release

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,75 +1,39 @@
 #
-# this is the release workflow that is triggered by a push to the main branch
+# this workflow will move the release flagged as 'pre-release' to the release named 'latest'
 #
-# this workflow requires a secret "GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK" to point to the google chat room
-# if not declared his workflow will set a warning and will exit gracefully (=> without an error)
+# see ./scripts/release.sh for details
 #
-# it will
-# - update the versions of all packages
-# - build the project
-# - @TODO test the project
-# - create a releases for all packages that have changed and add its artifacts to the release
-# - gather the workflow artifacts
-#
-name: 'release'
+name: 'release (manual workflow)'
 
 on:
-  push:
-    branches:
-      - main
-
-permissions:
-  # write-all is too much, but we need to write to packages
-  # see https://github.com/orgs/community/discussions/57724 for more info
-  contents: write
-  packages: write
-  attestations: write
-  id-token: write
+  # this workflow needs to be triggered manually
+  workflow_dispatch:
 
 jobs:
-  devcontainer:
-    uses: ./.github/workflows/build-devcontainer-image.yaml
-    secrets: inherit
-
   release:
     runs-on: ubuntu-latest
-    needs:
-      - devcontainer
+    # ensure only one pipeline is running this workflow at a time
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
-    if: "!contains(github.event.head_commit.message, 'skip release')"
     steps:
-      - name: checkout branch from git
-        uses: actions/checkout@v4
+      # only run on main branch
+      - name: Check branch
+        if: github.ref_name != 'main'
+        run: |
+          echo "::error::Workflow can only be run on branch 'main'"
+          exit 1
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
         with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          fetch-depth: 0
+          ref: '${{ github.ref_name }}'
 
-      - uses: './.github/shared/actions/devcontainer-shell-run'
-        name: build_project
-        with:
-          runCmd: |
-            pnpm install --frozen-lockfile
+      - name: release
+        run: |
+          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
+          export GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK="${{ secrets.GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK }}"
 
-            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
-            export GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK="${{ secrets.GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK }}"
-
-            pnpm release
-
-      - uses: './.github/shared/actions/devcontainer-shell-run'
-        id: gather_workflow_artifacts
-        name: gather_workflow_artifacts
-        with:
-          runCmd: |
-            pnpm exec ./scripts/_get-workflow-artefacts.sh
-
-      - name: attach workflow artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          # see https://github.com/actions/upload-artifact/issues/424
-          path: |-
-            ${{ steps.gather_workflow_artifacts.outputs.runCmdOutput }}
+          # by calling this script directly in the pipeline we dont need to install pnpm :-)
+          # pnpm release
+          ./scripts/release.sh
